# Generated by Django 5.2.8 on 2025-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_breed_slug_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name_zh',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
