# Generated by Django 5.2.8 on 2025-12-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_breed_name_zh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.URLField(unique=True),
        ),
    ]
