# Generated by Django 5.2.8 on 2025-12-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gamesession_user_question_breed_slug_roundrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrecord',
            name='correct_answer_slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundrecord',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
