# Generated by Django 5.2.8 on 2025-12-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gamesession_user_playerinfo_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundrecord',
            old_name='correct_answer_slug',
            new_name='correct_slug',
        ),
        migrations.RenameField(
            model_name='roundrecord',
            old_name='game',
            new_name='game_session',
        ),
        migrations.RenameField(
            model_name='roundrecord',
            old_name='selected_answer_slug',
            new_name='selected_slug',
        ),
    ]
