# Generated by Django 5.2.8 on 2025-12-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_correct_answer_slug_roundrecord_correct_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrecord',
            name='choices',
            field=models.JSONField(default=list),
        ),
    ]
