# Generated by Django 5.2.8 on 2025-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_roundrecord_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='introduction_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='introduction_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='origin_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='origin_zh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
