# Generated by Django 5.2.8 on 2025-12-22 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_breed_introduction_en_breed_introduction_zh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundrecord',
            name='choices',
        ),
        migrations.CreateModel(
            name='RoundRecordBreedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.breed')),
                ('round_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.roundrecord')),
            ],
        ),
    ]
