# Generated by Django 5.2.8 on 2025-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_roundrecord_choices_roundrecordbreedchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='nickname',
            field=models.CharField(default='Doggo Lover', max_length=100),
        ),
    ]
