# Generated by Django 5.2.8 on 2025-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_playerinfo_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='avg_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
