# Generated by Django 5.2.8 on 2025-12-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_gamesession_avg_accuracy_gamesession_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='is_finished',
        ),
    ]
