# Generated by Django 5.2.8 on 2026-01-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_gamesession_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.BigIntegerField(default=0)),
                ('total_rounds', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='correct_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breed',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HardestBreedStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(unique=True)),
                ('correct_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardest_stat', to='api.breed')),
            ],
        ),
    ]
