# Generated by Django 5.2.8 on 2026-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_globalstat_breed_correct_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstat',
            name='total_correct',
            field=models.BigIntegerField(default=0),
        ),
    ]
